stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    DEPLOY_PATH: "/var/www/my-new.liteforex.com"
  script:
    - pwd
    - if [ ! -d $DEPLOY_PATH ]; then mkdir $DEPLOY_PATH; fi
    - rsync -av --include-from './rsync-include.txt' --exclude-from './rsync-exclude.txt' --delete ./ $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - pwd
    - node -v
    - pm2 list
    - echo '@liteforex.com:registry=https://gitlab.liteforex.com/api/v4/packages/npm/'>.npmrc
    - echo '//gitlab.liteforex.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'>>.npmrc
    - npm install --production
    - npm run prod
    - pm2 startOrRestart ecosystem.config.js
  tags:
    - awssecure
  only:
    - master

